name: gh-page
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  deploy_gh_page:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Find my ip
        id: findIp
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.FIND_IP_URL }}
          method: 'GET'
          username: ${{ secrets.FIND_IP_USER }}
          password: ${{ secrets.FIND_IP_PASSWORD }}
      - name: Print ip
        run: echo ${{ fromJson(steps.findIp.outputs.response).ip }}
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ fromJson(steps.findIp.outputs.response).ip }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./public"
          target: ${{ secrets.DEPLOY_PATH }}